### ISSUE TITLE
Texto de links ao final de alguns capítulos

### ISSUE THREAD

**Issue by matEvangelista** [marcossancal/Biblia-Cat-lica#1]
Olá.

Creio que você construiu o .json com web scraping porque há várias ocorrorências do tipo "< judite 10 judite 12 >".
Textos deste tipo estão inseridos de maneira incorreta e quebram a formatação do .json, como se vê no exemplo abaixo.

![image](https://github.com/marcossancal/Biblia-Catolica/assets/39502131/27740b82-549b-4532-881d-c4fbe840383d)

Vou abrir um PR.

Obrigado pela iniciativa de colocar a bíblia católica em .json. Não aguentava mais ter que contar com versões protestantes.

**Comment by marcossancal** [comment]
foi com web scraping msm... passei o olho no genesis e num tinha visto erros... passou batido
